"use client";
import { FormEvent, useEffect, useState } from "react";

type Client={id:number;external_id:string;name:string;phone:string;email?:string;city?:string;status:string;last_contact_at?:string};
export default function ClientsPage(){
 const [clients,setClients]=useState<Client[]>([]),[q,setQ]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[city,setCity]=useState(""),[notice,setNotice]=useState("");
 const load=()=>fetch(`/api/clients?q=${encodeURIComponent(q)}`).then(r=>r.json()).then(x=>setClients(x.data||[])).catch(()=>setNotice("Impossible de charger les clients."));
 useEffect(()=>{load()},[]);
 const add=async(e:FormEvent)=>{e.preventDefault();const r=await fetch("/api/clients",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,phone,email,city})});const x=await r.json();if(!r.ok)return setNotice(x.error||"Erreur");setName("");setPhone("");setEmail("");setCity("");setNotice("Client créé avec succès.");load()};
 return <main style={{minHeight:"100vh",background:"#f7f9fc",padding:24,fontFamily:"Arial"}}><div style={{maxWidth:1200,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><h1 style={{margin:0}}>♙ Clients</h1><p style={{color:"#68758a"}}>CRM réel connecté à PostgreSQL</p></div><a href="/" style={{textDecoration:"none",padding:"10px 14px",background:"#1476e8",color:"white",borderRadius:7}}>← Tableau de bord</a></header>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2",marginBottom:16}}><h2 style={{fontSize:16}}>Nouveau client</h2><form onSubmit={add} style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10}}>{[["Nom",name,setName,true],["Téléphone",phone,setPhone,true],["Email",email,setEmail,false],["Ville",city,setCity,false]].map(([label,value,setter,required])=><input key={label as string} placeholder={label as string} value={value as string} onChange={e=>(setter as any)(e.target.value)} required={required as boolean} style={{padding:10,border:"1px solid #dce2eb",borderRadius:6}}/>)}<button style={{padding:10,border:0,borderRadius:6,background:"#43bd66",color:"white",fontWeight:700}}>Ajouter</button></form></section>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2"}}><div style={{display:"flex",gap:10,marginBottom:14}}><input placeholder="Rechercher nom, téléphone, email..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} style={{flex:1,padding:10,border:"1px solid #dce2eb",borderRadius:6}}/><button onClick={load} style={{padding:"10px 16px",border:0,borderRadius:6,background:"#1476e8",color:"white"}}>Rechercher</button><button onClick={()=>window.location.href="/api/export/calls"} style={{padding:"10px 16px",border:"1px solid #dce2eb",background:"white",borderRadius:6}}>CSV appels</button></div><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["ID","Client","Téléphone","Email","Ville","Statut","Dernier contact"].map(h=><th key={h} style={{textAlign:"left",padding:10,borderBottom:"1px solid #e5eaf2",fontSize:12}}>{h}</th>)}</tr></thead><tbody>{clients.map(c=><tr key={c.id}>{[c.external_id,c.name,c.phone,c.email||"—",c.city||"—",c.status,c.last_contact_at?new Date(c.last_contact_at).toLocaleString("fr-FR"):"—"].map((v,i)=><td key={i} style={{padding:10,borderBottom:"1px solid #eef1f5",fontSize:12}}>{v}</td>)}</tr>)}</tbody></table>{!clients.length&&<p style={{textAlign:"center",color:"#68758a",padding:30}}>Aucun client trouvé.</p>}</section>{notice&&<button onClick={()=>setNotice("")} style={{position:"fixed",right:20,bottom:20,padding:14,border:0,borderRadius:8,background:"#111b2f",color:"white"}}>{notice} ×</button>}</div></main>
}
