"use client";

import { useEffect, useMemo, useState } from "react";

type Call = { id:number; status:string; name:string; phone:string; campaign:string; duration:number; outcome?:string; intent?:string };
type Dashboard = { stats:{today:number;success:number;conversions:number;waiting:number;failures:number}; calls:Call[]; campaigns:{name:string;progress:number;status:string}[]; actions:{name:string;time:string;type:string}[]; aiSummary:string[]; client?:{external_id:string;name:string;phone:string;email:string;city:string;status:string} };
const fallback: Dashboard = {stats:{today:1248,success:842,conversions:128,waiting:356,failures:50},calls:[{id:1,status:"in_progress",name:"Jean Mukendi",phone:"+243 81 234 5678",campaign:"Rappel RDV",duration:154,intent:"Replanifier rendez-vous"},{id:2,status:"ringing",name:"Marie-Louise K.",phone:"+243 81 987 6543",campaign:"Offre Spéciale",duration:15},{id:3,status:"waiting",name:"Paul Tshibangu",phone:"+243 85 111 2233",campaign:"Enquête Client",duration:0},{id:4,status:"busy",name:"Sophie Lumbu",phone:"+243 81 555 6677",campaign:"Rappel RDV",duration:0},{id:5,status:"no_answer",name:"Alain Banza",phone:"+243 99 888 7766",campaign:"Offre Spéciale",duration:0}],campaigns:[{name:"Rappel RDV",progress:72,status:"Active"},{name:"Offre Spéciale",progress:45,status:"Active"},{name:"Enquête Client",progress:60,status:"Active"}],actions:[{name:"Rappeler Marie-Louise K.",time:"Aujourd'hui à 14:30",type:"calendar"},{name:"Relancer Paul Tshibangu",time:"Demain à 09:00",type:"phone"},{name:"Envoyer offre par email",time:"Sophie Lumbu",type:"mail"}],aiSummary:["Aujourd'hui, le taux de réussite est bon avec 67.6% d'appels aboutis.","Les clients sont réceptifs aux offres.","Plusieurs demandes de reprogrammation de rendez-vous.","Taux de conversion en hausse.","Recommandation : augmenter les rappels entre 10h et 12h."],client:{external_id:"CLI-000123",name:"Jean Mukendi",phone:"+243 81 234 5678",email:"jean.mukendi@example.com",city:"Kinshasa",status:"Client actif"}};
const statusLabel:Record<string,string>={in_progress:"En cours",ringing:"Sonnerie",waiting:"En attente",busy:"Occupé",no_answer:"Sans réponse",completed:"Réussi"};
function fmtDuration(sec:number){return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
export default function Home(){
 const [data,setData]=useState<Dashboard>(fallback);const [query,setQuery]=useState("");const [paused,setPaused]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{fetch("/api/dashboard").then(r=>r.ok?r.json():null).then(d=>d&&setData(d)).catch(()=>{});},[]);
 const calls=useMemo(()=>data.calls.filter(c=>`${c.name} ${c.phone} ${c.campaign}`.toLowerCase().includes(query.toLowerCase())),[data.calls,query]);
 const notify=(text:string)=>setNotice(text);
 const navAction=(t:string)=>{if(t==="Exportations")window.location.href="/api/export/calls";else if(t==="Historique des appels")document.querySelector(".calls-card")?.scrollIntoView({behavior:"smooth"});else notify(`${t} : module sélectionné.`)};
 const startCall=async(c:Call)=>{notify(`Appel vers ${c.name} enregistré dans la file.`);await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:c.id})}).catch(()=>{});};
 const stats=[["☎","Appels aujourd'hui",data.stats.today,"+12.5% vs hier","blue"],["✓","Appels réussis",data.stats.success,"67.6% de réussite","green"],["●","Conversions",data.stats.conversions,"10.2% de conversion","purple"],["◷","En attente",data.stats.waiting,"À rappeler","orange"],["⌁","Échecs",data.stats.failures,"4.0% d'échec","cyan"]];
 return <main className="autodialer-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon">☎</div><div><b>AutoDialer IA</b><small>Voice AI + CRM</small></div></div><nav>{[["⌂","Tableau de bord"],["▣","Campagnes"],["☷","Listes d'appels"],["☎","Auto-Dialer"],["↻","File d'appels"],["♙","Clients"],["♧","Contacts"],["▣","Rendez-vous"],["◉","Segments"],["☎","Appels en cours"],["◷","Historique des appels"],["◉","Enregistrements"],["≡","Transcriptions"],["▥","Rapports"],["◒","Statistiques"],["⇩","Exportations"],["⚙","Utilisateurs"],["♙","Rôles & Permissions"],["⚙","Paramètres"],["⌘","Intégrations"],["≡","Logs & Audit"]].map(([i,t],idx)=><button key={t} className={idx===0?"nav active":"nav"} onClick={()=>navAction(t)}><span>{i}</span>{t}</button>)}</nav><div className="profile"><div className="avatar">R</div><div><b>Rogerio Kabongo</b><small>Administrateur</small><small className="online">● En ligne</small></div></div></aside>
 <section className="workspace"><header className="topbar"><div><h1>☰ <span>Tableau de bord</span></h1><small>Vue d'ensemble du système</small></div><div className="top-actions"><span className="operational">● Système opérationnel</span><span>◎ Français⌄</span><span>♧ <sup>6</sup></span><button onClick={()=>notify("Utilisez F11 pour le plein écran du navigateur.")}>⛶</button></div></header><div className="stats-grid">{stats.map(([icon,title,value,sub,color])=><div className={`stat ${color}`} key={title}><div className="stat-icon">{icon}</div><div><small>{title}</small><strong>{value}</strong><span>{sub}</span></div></div>)}</div>
 <div className="content-grid"><div className="main-column"><section className="card calls-card"><div className="card-head"><h2>Appels en temps réel</h2><button className="link-btn" onClick={()=>navAction("Historique des appels")}>Voir tout</button><input aria-label="Rechercher" placeholder="Rechercher un client..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Statut</th><th>Client</th><th>Téléphone</th><th>Campagne</th><th>Durée</th><th></th></tr></thead><tbody>{calls.map(c=><tr key={c.id}><td><span className={`pill ${c.status}`}>{statusLabel[c.status]}</span></td><td><b>{c.name}</b></td><td>{c.phone}</td><td>{c.campaign}</td><td>{c.duration?fmtDuration(c.duration):"-"}</td><td><button className="call-btn" onClick={()=>startCall(c)}>☎</button></td></tr>)}</tbody></table></div></section>
 <div className="lower-grid"><section className="card"><div className="card-head"><h2>Campagnes actives</h2><button className="link-btn" onClick={()=>navAction("Campagnes")}>Voir toutes</button></div>{data.campaigns.map(c=><div className="campaign" key={c.name}><div><b>{c.name}</b><span>{c.status}</span></div><small>Progression</small><div className="progress"><i style={{width:`${c.progress}%`}}/></div><em>{c.progress}%</em></div>)}</section><section className="card"><div className="card-head"><h2>Prochaines actions IA</h2></div>{data.actions.map(a=><div className="action" key={a.name}><div className="action-icon">{a.type==="calendar"?"▣":a.type==="phone"?"☎":"✉"}</div><div><b>{a.name}</b><small>{a.time}</small></div><span>IA suggéré</span></div>)}<button className="wide-btn" onClick={()=>notify("Actions IA : liste complète chargée.")}>Voir toutes les actions</button></section><section className="card"><div className="card-head"><h2>Résumé IA quotidien</h2><a>Généré par IA</a></div><div className="ai-summary">{data.aiSummary.map((s,i)=><p key={s}>{i===0?"":"✓"} {s}</p>)}</div><button className="wide-btn" onClick={()=>notify("Analyse IA complète disponible après connexion du fournisseur LLM.")}>✦ Voir analyse complète</button></section></div></div>
 <aside className="live-panel"><div className="live-head"><b>Appel actif avec IA</b><span>En cours</span></div><div className="robot">◉<div className="waves">∿∿∿</div></div><h2>{data.client?.name}</h2><p>{data.client?.phone}</p><div className="client-badges"><span>Client existant</span><span>ID: {data.client?.external_id}</span></div><div className="conversation"><h3>Conversation en cours</h3><small>Transcription en temps réel</small><p><b>IA:</b> Bonjour Jean, ici l'assistant de l'entreprise DEVARYX. Je vous appelle concernant votre rendez-vous de demain. Êtes-vous toujours disponible ?</p><p><b>Client:</b> Non, je préfère vendredi matin.</p><p><b>IA:</b> Pas de problème. Vendredi matin vous convient à quelle heure ?</p><p><b>Client:</b> Vers 10h00 ça me va.</p><p><b>IA:</b> Parfait, c'est noté ✓. Votre rendez-vous est donc reprogrammé pour vendredi à 10h00. Merci Jean, bonne journée !</p></div><div className="intent"><small>Intention détectée par IA</small><b>Replanifier rendez-vous</b><span>✓</span></div><div className="controls"><button onClick={()=>notify("Haut-parleur activé.")}>🔊<small>Haut-parleur</small></button><button onClick={()=>setPaused(!paused)}>{paused?"▶":"Ⅱ"}<small>{paused?"Reprendre":"Pause"}</small></button><button className="hangup" onClick={()=>notify("Appel terminé et journalisé.")}>☎<small>Raccrocher</small></button></div><div className="client-info"><h3>Informations client <a onClick={()=>notify("Profil client sélectionné.")}>Voir le profil</a></h3><p>Nom: <b>{data.client?.name}</b></p><p>Téléphone: <b>{data.client?.phone}</b></p><p>Email: <b>{data.client?.email}</b></p><p>Ville: <b>{data.client?.city}</b></p><p>Dernier contact: <b>15/05/2024</b></p><p>Statut: <b className="client-active">Client actif</b></p></div></aside></div><footer className="techbar"><span>✦ IA Conversationnelle <small>OpenAI / GPT-4</small></span><span>♬ Reconnaissance vocale <small>Whisper</small></span><span>◯ Voix naturelle <small>ElevenLabs</small></span><span>◉ Téléphonie <small>Twilio / Vonage</small></span><span>▤ Base de données <small>PostgreSQL</small></span><span>♙ Sécurité <small>Chiffrage AES-256</small></span></footer>{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice} ×</button>}</section></main>
}