"use client";
import { useState } from "react";

type Mode = "consult" | "respond" | "negotiate";
const providers = ["claude","openai","deepseek","gemini","mistral","groq","openrouter","together","xai","cohere","ollama"] as const;
const config: Record<Mode,{title:string;subtitle:string;placeholder:string;system:string}> = {
  consult:{title:"AI Consult",subtitle:"Analyse commerciale et recommandations avant l’action.",placeholder:"Décris la situation, le client, l’offre et ton objectif…",system:"Tu es le consultant commercial IA d’OmniComm 360. Analyse la situation, identifie les risques et opportunités, puis propose un plan d’action concret. Ne prétends jamais connaître des informations absentes du contexte."},
  respond:{title:"AI Attend Client & Respond",subtitle:"Prépare une réponse professionnelle, rapide et adaptée au client.",placeholder:"Colle le message du client et indique le contexte…",system:"Tu es l’assistant relation client d’OmniComm 360. Comprends le message du client, détecte son intention et rédige une réponse claire, empathique, professionnelle et orientée solution. N’invente ni prix, ni engagement, ni donnée client."},
  negotiate:{title:"AI Coach Client & Négociation",subtitle:"Coaching commercial pour conduire une négociation gagnant-gagnant.",placeholder:"Décris la négociation, la demande du client, tes limites et ton objectif…",system:"Tu es le coach commercial et négociateur IA d’OmniComm 360. Aide le commercial à préparer et conduire une négociation éthique: objectifs, concessions, objections, arguments, questions et prochaine étape. N’encourage pas la tromperie, la pression abusive ou les promesses non autorisées."}
};
export default function AiCommercial({mode}:{mode:Mode}){
 const c=config[mode]; const [provider,setProvider]=useState("claude"); const [prompt,setPrompt]=useState(""); const [answer,setAnswer]=useState(""); const [model,setModel]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const run=async()=>{if(!prompt.trim())return;setLoading(true);setError("");setAnswer("");try{const r=await fetch("/api/ai/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:`MODE: ${c.title}\n\n${prompt}`,provider,system:c.system})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur IA");setAnswer(d.text||"");setModel(d.model||provider)}catch(e){setError(e instanceof Error?e.message:"Erreur IA")}finally{setLoading(false)}};
 return <section className="space-y-5"><div><div className="text-xs font-mono text-violet-400">IA COMMERCIALE</div><h1 className="text-3xl font-bold text-white">{c.title}</h1><p className="text-slate-400 mt-1">{c.subtitle}</p></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2 rounded-xl border border-[#1c2a4a] bg-[#080e1f] p-5"><div className="flex items-center gap-3 mb-4"><label className="text-sm text-slate-300">LLM</label><select value={provider} onChange={e=>setProvider(e.target.value)} className="rounded-lg bg-[#050b18] border border-[#1c2a4a] px-3 py-2 text-white">{providers.map(p=><option key={p} value={p}>{p}{p==="claude"?" — défaut":""}</option>)}</select></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={c.placeholder} className="w-full min-h-52 rounded-lg bg-[#050b18] border border-[#1c2a4a] px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-violet-500"/><button onClick={run} disabled={loading||!prompt.trim()} className="mt-3 rounded-lg bg-violet-600 hover:bg-violet-500 disabled:opacity-50 px-5 py-2.5 font-semibold text-white">{loading?"Analyse en cours…":"Lancer l’IA"}</button>{error&&<div className="mt-4 rounded-lg border border-rose-500/40 bg-rose-500/10 p-3 text-rose-300">{error}</div>}{answer&&<div className="mt-5 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-4"><div className="text-xs text-emerald-300 mb-2">Réponse IA · {model}</div><div className="whitespace-pre-wrap text-slate-200 leading-7">{answer}</div></div>}</div><aside className="rounded-xl border border-[#1c2a4a] bg-[#080e1f] p-5"><h2 className="font-bold text-white">Capacités</h2><ul className="mt-3 space-y-3 text-sm text-slate-400"><li>🧠 Analyse du contexte client</li><li>💬 Réponse assistée</li><li>🎯 Arguments et objections</li><li>🤝 Coaching de négociation</li><li>🔄 Multi-LLM avec Claude par défaut</li><li>📝 Action tracée dans l’historique</li></ul></aside></div></section>
}
