"use client";
import { useEffect, useState } from "react";

type Client={id:number;external_id:string;name:string;phone:string;status:string;last_contact_at?:string};

type CallResult={ok:boolean;name?:string;phone?:string;callSid?:string;error?:string};

export default function AutoDialerPage(){
 const [clients,setClients]=useState<Client[]>([]),[q,setQ]=useState(""),[selected,setSelected]=useState<number[]>([]),[running,setRunning]=useState(false),[index,setIndex]=useState(0),[notice,setNotice]=useState(""),[campaign,setCampaign]=useState("AutoDialer IA"),[lastResult,setLastResult]=useState<CallResult|null>(null),[health,setHealth]=useState<{configured:boolean;checks?:Record<string,boolean>}|null>(null);
 const load=()=>fetch(`/api/clients?q=${encodeURIComponent(q)}`).then(r=>r.json()).then(x=>setClients(x.data||[])).catch(()=>setNotice("Impossible de charger la liste."));
 const checkHealth=()=>fetch("/api/voice/health").then(r=>r.json()).then(setHealth).catch(()=>setHealth({configured:false}));
 useEffect(()=>{load();checkHealth()},[]);
 const toggle=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const callOne=async(id:number):Promise<CallResult>=>{try{const r=await fetch("/api/voice/campaign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:id,campaign})});const x=await r.json().catch(()=>({error:"Réponse serveur invalide"}));if(!r.ok)throw new Error(x.error||`Erreur HTTP ${r.status}`);return x}catch(e){return {ok:false,error:e instanceof Error?e.message:"Appel impossible"}}};
 const start=async()=>{if(!selected.length)return setNotice("Sélectionnez au moins un numéro.");if(health&&!health.configured)return setNotice("Téléphonie non configurée : vérifiez Twilio + DATABASE_URL + APP_URL dans Vercel.");setRunning(true);setIndex(0);setLastResult(null);let ok=0,failed=0;for(let i=0;i<selected.length;i++){setIndex(i+1);const result=await callOne(selected[i]);setLastResult(result);if(result.ok){ok++;setNotice(`✓ Appel lancé : ${result.name} — ${result.phone}`)}else{failed++;setNotice(`✗ Échec : ${result.error}`)}if(i<selected.length-1)await new Promise(r=>setTimeout(r,1200))}setRunning(false);setNotice(failed?`Terminé : ${ok} appel(s) lancé(s), ${failed} échec(s).`:`Terminé : ${ok} appel(s) lancé(s).`);load()};
 const active=clients.filter(c=>c.status==="active");
 return <main style={{minHeight:"100vh",background:"#f7f9fc",padding:24,fontFamily:"Arial",fontSize:17}}><div style={{maxWidth:1250,margin:"auto"}}>
 <header style={{marginBottom:18}}><h1 style={{margin:0,fontSize:30}}>📞 AutoDialer IA</h1><p style={{color:"#68758a"}}>Liste de téléphones et cellulaires · appels automatiques via Twilio</p>{health&&<div style={{marginTop:8,fontWeight:700,color:health.configured?"#16803c":"#b42318"}}>{health.configured?"● Téléphonie configurée":"● Téléphonie non configurée"}</div>}</header>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2",marginBottom:16}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><input value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="Nom de campagne" style={{padding:12,fontSize:17,border:"1px solid #dce2eb",borderRadius:6,minWidth:260}}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Rechercher nom ou téléphone..." style={{padding:12,fontSize:17,border:"1px solid #dce2eb",borderRadius:6,flex:1,minWidth:250}}/><button onClick={load} style={{padding:"12px 16px",fontSize:17,border:0,borderRadius:6,background:"#1476e8",color:"white"}}>Rechercher</button><button onClick={()=>setSelected(active.map(c=>c.id))} style={{padding:"12px 16px",fontSize:17,border:"1px solid #dce2eb",background:"white",borderRadius:6}}>Tout sélectionner</button><button disabled={running} onClick={start} style={{padding:"12px 18px",fontSize:17,border:0,borderRadius:6,background:running?"#9aa5b5":"#43bd66",color:"white",fontWeight:700}}>{running?`Appels ${index}/${selected.length}…`:`Lancer ${selected.length} appels`}</button></div></section>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2"}}><div style={{marginBottom:12,color:"#68758a"}}>{active.length} numéros actifs · {selected.length} sélectionnés</div><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["","ID","Nom","Téléphone / Cellulaire","Statut","Dernier contact"].map(h=><th key={h} style={{textAlign:"left",padding:12,borderBottom:"1px solid #e5eaf2"}}>{h}</th>)}</tr></thead><tbody>{clients.map(c=><tr key={c.id}><td style={{padding:12}}><input type="checkbox" style={{width:20,height:20}} checked={selected.includes(c.id)} disabled={c.status!=="active"||running} onChange={()=>toggle(c.id)}/></td><td style={{padding:12}}>{c.external_id}</td><td style={{padding:12,fontWeight:600}}>{c.name}</td><td style={{padding:12,fontFamily:"monospace"}}>{c.phone}</td><td style={{padding:12}}>{c.status}</td><td style={{padding:12}}>{c.last_contact_at?new Date(c.last_contact_at).toLocaleString("fr-FR"):"—"}</td></tr>)}</tbody></table>{!clients.length&&<p style={{textAlign:"center",padding:30,color:"#68758a"}}>Aucun numéro trouvé.</p>}</section>
 {lastResult&&!lastResult.ok&&<section style={{marginTop:16,padding:16,borderRadius:10,background:"#fff1f0",border:"1px solid #f2b8b5",color:"#8b1e1e"}}><b>Dernier appel : échec</b><div style={{marginTop:6}}>{lastResult.error}</div></section>}
 {notice&&<button onClick={()=>setNotice("")} style={{position:"fixed",right:20,bottom:20,padding:16,fontSize:17,border:0,borderRadius:8,background:"#111b2f",color:"white"}}>{notice} ×</button>}
 </div></main>
}
