"use client";
import { useEffect, useState } from "react";

type Client={id:number;external_id:string;name:string;phone:string;status:string;last_contact_at?:string};

export default function AutoDialerPage(){
 const [clients,setClients]=useState<Client[]>([]),[q,setQ]=useState(""),[selected,setSelected]=useState<number[]>([]),[running,setRunning]=useState(false),[index,setIndex]=useState(0),[notice,setNotice]=useState(""),[campaign,setCampaign]=useState("AutoDialer IA");
 const load=()=>fetch(`/api/clients?q=${encodeURIComponent(q)}`).then(r=>r.json()).then(x=>setClients(x.data||[])).catch(()=>setNotice("Impossible de charger la liste."));
 useEffect(()=>{load()},[]);
 const toggle=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const callOne=async(id:number)=>{const r=await fetch("/api/voice/campaign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:id,campaign})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Appel impossible");return x};
 const start=async()=>{if(!selected.length)return setNotice("Sélectionnez au moins un numéro.");setRunning(true);setIndex(0);for(let i=0;i<selected.length;i++){setIndex(i+1);try{const x=await callOne(selected[i]);setNotice(`Appel lancé : ${x.name} — ${x.phone}`)}catch(e){setNotice(e instanceof Error?e.message:"Erreur d'appel")}await new Promise(r=>setTimeout(r,1200))}setRunning(false);setNotice("Campagne terminée.");load()};
 const active=clients.filter(c=>c.status==="active");
 return <main style={{minHeight:"100vh",background:"#f7f9fc",padding:24,fontFamily:"Arial"}}><div style={{maxWidth:1250,margin:"auto"}}>
 <header style={{marginBottom:18}}><h1 style={{margin:0}}>📞 AutoDialer IA</h1><p style={{color:"#68758a"}}>Liste de téléphones et cellulaires · appels automatiques via Twilio</p></header>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2",marginBottom:16}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><input value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="Nom de campagne" style={{padding:10,border:"1px solid #dce2eb",borderRadius:6,minWidth:260}}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Rechercher nom ou téléphone..." style={{padding:10,border:"1px solid #dce2eb",borderRadius:6,flex:1,minWidth:250}}/><button onClick={load} style={{padding:"10px 16px",border:0,borderRadius:6,background:"#1476e8",color:"white"}}>Rechercher</button><button onClick={()=>setSelected(active.map(c=>c.id))} style={{padding:"10px 16px",border:"1px solid #dce2eb",background:"white",borderRadius:6}}>Tout sélectionner</button><button disabled={running} onClick={start} style={{padding:"10px 18px",border:0,borderRadius:6,background:running?"#9aa5b5":"#43bd66",color:"white",fontWeight:700}}>{running?`Appels ${index}/${selected.length}…`:`Lancer ${selected.length} appels`}</button></div></section>
 <section style={{background:"white",padding:18,borderRadius:10,border:"1px solid #e5eaf2"}}><div style={{marginBottom:12,color:"#68758a",fontSize:13}}>{active.length} numéros actifs · {selected.length} sélectionnés</div><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["","ID","Nom","Téléphone / Cellulaire","Statut","Dernier contact"].map(h=><th key={h} style={{textAlign:"left",padding:10,borderBottom:"1px solid #e5eaf2",fontSize:12}}>{h}</th>)}</tr></thead><tbody>{clients.map(c=><tr key={c.id}><td style={{padding:10}}><input type="checkbox" checked={selected.includes(c.id)} disabled={c.status!=="active"||running} onChange={()=>toggle(c.id)}/></td><td style={{padding:10,fontSize:12}}>{c.external_id}</td><td style={{padding:10,fontSize:13,fontWeight:600}}>{c.name}</td><td style={{padding:10,fontFamily:"monospace"}}>{c.phone}</td><td style={{padding:10}}>{c.status}</td><td style={{padding:10,fontSize:12}}>{c.last_contact_at?new Date(c.last_contact_at).toLocaleString("fr-FR"):"—"}</td></tr>)}</tbody></table>{!clients.length&&<p style={{textAlign:"center",padding:30,color:"#68758a"}}>Aucun numéro trouvé.</p>}</section>
 {notice&&<button onClick={()=>setNotice("")} style={{position:"fixed",right:20,bottom:20,padding:14,border:0,borderRadius:8,background:"#111b2f",color:"white"}}>{notice} ×</button>}
 </div></main>
}
